---
title: "dplyr sample codes"
author: "Sedi Abbasnasab"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
require(dplyr)
```
#load data
```{r}
demo <- read.csv("demographics.csv")
View(demo)
```
#filtering
#owners with the income greater than 55
```{r}
demo2 <- filter(demo, income>55)
View(demo2)
```
#owners with income equal to 60
```{r}
demo2 <- filter(demo, income==60)
View(demo2)
```
#married owners
```{r}
demo2 <- filter(demo, marital=='Married')
View(demo2)
```
#married owners with the income greater than 55
```{r}
demo2 <- filter(demo, marital=='Married', income>55)
View(demo2)
```
#multiple conditions
```{r}
demo2 <- filter(demo, marital=='Married', income>55, carcat=='Luxury')
View(demo2)
```
#owners with age between 35 and 45
```{r}
demo2 <- filter(demo, age>=35, age<=45)
View(demo2)
```
#owners who are married OR the income greater than 55
```{r}
demo2 <- filter(demo, income>55 | marital=='Married')
View(demo2)
```
#owners aged 42, 45 and 60
```{r}
demo2 <- filter(demo, age %in% c(42, 45, 60))
View(demo2)
```
#owners with the ages different from 42, 45 and 60
```{r}
demo2 <- filter(demo, !age %in% c(42, 45, 60))
View(demo2)
```